#!/usr/bin/env python3
"""Generate docs/models.md from the model catalogs.

Both catalogs are the source of truth: `src/config.py` for the terminal coding agent
and `src/embed_catalog.py` for embedded/SDK use. Hand-maintained copies of these tables
drift the moment a row is added, so they are generated instead.

    python scripts/generate_model_docs.py          # rewrite docs/models.md
    python scripts/generate_model_docs.py --check  # fail if they are stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.config import DEFAULT_DIRECT_MODEL_CATALOG  # noqa: E402
from src.embed_catalog import (  # noqa: E402
    EMBED_MODEL_CATALOG,
    EMBED_USE_CASES,
    TARGET_DEVICE_PRESETS,
    resident_mb,
)

DOCS_PATH = REPO_ROOT / "docs" / "models.md"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines)


def coding_tables() -> tuple[str, str]:
    general: list[list[str]] = []
    unified: list[list[str]] = []
    for row in DEFAULT_DIRECT_MODEL_CATALOG:
        entry = [str(row["label"]), f"{float(row['max_ram_gb']):.1f}", f"{float(row['model_size_mb']) / 1024:.1f} GB"]
        (unified if row.get("unified_memory_only") else general).append(entry)
    headers = ["Model", "Configured `max_ram_gb`", "Weights on disk"]
    return _table(headers, general), _table(headers, unified)


def embed_table(context_tokens: int = 4096) -> str:
    rows = []
    for row in EMBED_MODEL_CATALOG:
        rows.append(
            [
                str(row["label"]),
                str(row["quant"]),
                f"{resident_mb(row, context_tokens) / 1024:.1f} GB",
                f"~{row['ttft_ms']} ms",
                f"~{row['tokens_per_sec']} tok/s",
                ", ".join(row["use_cases"]),
            ]
        )
    return _table(
        ["Model", "Quant", f"Resident @ {context_tokens} ctx", "First token", "Throughput", "Use cases"],
        rows,
    )


def use_case_table() -> str:
    return _table(
        ["Use case", "`--use-case`", "Latency target", "What it is"],
        [
            [str(row["label"]), f"`{row['id']}`", f"{row['max_ttft_ms']} ms to first token", str(row["detail"])]
            for row in EMBED_USE_CASES
        ],
    )


def target_table() -> str:
    return _table(
        ["Target device", "`--target`", "Device memory", "Default model budget"],
        [
            [
                str(row["label"]),
                f"`{row['id']}`",
                f"{float(row['total_gb']):.0f} GB",
                f"{float(row['budget_gb']):.0f} GB",
            ]
            for row in TARGET_DEVICE_PRESETS
        ],
    )


def render_docs() -> str:
    general, unified = coding_tables()
    return f"""# Choosing a model

<!-- Generated by scripts/generate_model_docs.py. Do not edit by hand. -->

Which model you want depends on what it is doing and what it is running on. The two
paths pick from different catalogs, because they optimise for different things.

## Terminal coding agent

`openjet setup` profiles the machine it runs on and picks the strongest coding model
that machine can hold. Capability wins here, so aggressive quant on a large model is a
good trade. `max_ram_gb` is the configured setup target for that row.

**General (any GPU/RAM):**

{general}

**Unified memory only:**

{unified}

## Embedded in your application

`openjet project` provisions a model for an application that embeds the SDK. The target
device is declared rather than detected — the machine you build on is not the machine
you ship to — and the budget is the slice your application concedes to the model, not
the whole device.

```bash
openjet project --use-case dialogue --target handheld --budget 4
```

### Use cases

{use_case_table()}

The latency target is enforced during selection: a generous budget will not buy a model
that misses the first-token deadline for that use case.

Each use case also carries a quant floor. Damage from aggressive quantization shows up
far faster on a small model than on a 27B, and schema adherence degrades before prose
does — so `extract` and `classify` will not take a quant that `chat` and `summarize`
tolerate. A larger model at a quant below the floor loses to a smaller one above it.

### Target devices

{target_table()}

### Catalog

{embed_table()}

Throughput and first-token figures are planning estimates scaled off active parameter
count, not measured numbers. Run `openjet benchmark` on real target hardware before
committing to a latency budget.

### How a model is picked

The catalog is ordered weakest to strongest, and selection walks it from the strongest
end, taking the first row that clears every constraint at once:

1. the row supports the use case
2. its quant is at or above that use case's floor
3. weights plus KV cache at your context window fit inside the budget
4. its estimated first token lands inside the use case's latency target

If nothing clears all four, provisioning fails and prints why each candidate was
rejected. It never silently downgrades — a model that misses the latency target for a
game NPC is not a smaller win, it is a broken feature. Raise the budget, shorten the
context, or pick a use case with a looser deadline.

## Sizing the context window

The KV cache is charged against your budget alongside the weights, and it grows linearly
with the context window. A model that fits at 4k may not fit at 32k. `openjet project`
prompts for the context window and accounts for it during selection.

Two consequences worth planning around:

- `summarize` and RAG workloads spend most of their budget on cache rather than weights,
  so a long context often means a smaller model, not a bigger budget.
- The budget is what your application concedes, not what the device has. On a 16GB
  handheld with a 4GB budget, the other 12GB is your game, not headroom.

## Related

- [SDK quickstart](sdk/quickstart.md) — provision, embed, and ship an on-device model
- [CLI usage](usage/cli.md#start-commands) — every `openjet project` flag
- [Project configuration](configuration.md#project-configuration-openjetconfigyaml) — the `.openjet/` overlay
- [Benchmarking](benchmarking.md) — replace these estimates with measurements
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero if the docs are stale")
    args = parser.parse_args()

    body = render_docs()
    stale = not DOCS_PATH.exists() or DOCS_PATH.read_text() != body

    if args.check:
        if stale:
            print(f"stale: {DOCS_PATH.relative_to(REPO_ROOT)}")
            print("Run `python scripts/generate_model_docs.py` to update.")
        return 1 if stale else 0

    DOCS_PATH.write_text(body)
    print(f"wrote {DOCS_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
