"""Context-layer facade.

This layer owns prompt shaping, context budgeting, harness state, and durable memory.
"""

from ..agent import ActionKind, Agent, AgentEvent
from ..harness import (
    HarnessSessionStore,
    HarnessState,
    TodoItem,
    TurnBudget,
    active_step,
    active_todo,
    allowed_tools_for_state,
    available_skill_names,
    build_turn_context,
    clear_preferred_skills,
    clear_todos,
    enter_plan_mode,
    exit_plan_mode,
    infer_stage,
    mark_verification_pending,
    pre_edit_gate_message,
    quality_gate_doc_labels,
    quality_gate_messages,
    record_verification_result,
    record_verification_skip,
    set_plan_approved,
    set_mode,
    set_preferred_skills,
    upsert_todos,
    update_state_after_turn,
    update_state_for_user_message,
    verification_gate_message,
)
from ..multimodal import build_user_content, content_to_plain_text, estimate_message_content_tokens
from ..memory_reflection import reflect_agent_persistent_memory, refresh_agent_system_prompt
from ..persistent_memory import (
    build_system_prompt,
    load_persistent_memory,
    update_persistent_memory,
)
from ..runtime_limits import ContextBudget, derive_context_budget, estimate_tokens, read_memory_snapshot

__all__ = [
    "ActionKind",
    "Agent",
    "AgentEvent",
    "ContextBudget",
    "HarnessSessionStore",
    "HarnessState",
    "TodoItem",
    "TurnBudget",
    "active_step",
    "active_todo",
    "allowed_tools_for_state",
    "available_skill_names",
    "build_system_prompt",
    "build_turn_context",
    "build_user_content",
    "clear_preferred_skills",
    "clear_todos",
    "content_to_plain_text",
    "derive_context_budget",
    "enter_plan_mode",
    "estimate_message_content_tokens",
    "estimate_tokens",
    "exit_plan_mode",
    "infer_stage",
    "mark_verification_pending",
    "load_persistent_memory",
    "pre_edit_gate_message",
    "quality_gate_doc_labels",
    "quality_gate_messages",
    "read_memory_snapshot",
    "reflect_agent_persistent_memory",
    "record_verification_result",
    "record_verification_skip",
    "refresh_agent_system_prompt",
    "set_plan_approved",
    "set_mode",
    "set_preferred_skills",
    "upsert_todos",
    "update_persistent_memory",
    "update_state_after_turn",
    "update_state_for_user_message",
    "verification_gate_message",
]
